---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Building Web Apps with R Shiny (2022)

<!-- badges: start -->
<!-- badges: end -->

[CodeHorizons Registration Page](https://codehorizons.com/Seminars/building-web-apps-with-r-shiny/)

Shiny apps let you make web applications that do anything you can code in R. For example, you can share your data analysis in a dynamic way with people who don’t use R, collect and visualize data, or even make data aRt.

While there is a wealth of material available on the internet to help you get started with Shiny, it can be difficult to see how everything fits together. This class will take a predominantly live coding approach, rather than a lecture-only approach, so you can code along with the instructor and deal with the inevitable bugs and roadblocks together.

This class will teach you the basics of Shiny app programming, giving you skills that will form the basis of almost any app you want to build. By the end of the class, you will have created a custom app that collects and saves data, and allows users to dynamically visualize the data.

The seminar will use resources from Lisa DeBruine's book, [Building Web Apps with R Shiny](https://debruine.github.io/shinyintro/).


## Outline

### Day 1

[Your First Shiny App](https://debruine.github.io/shinyintro/first-app.html) ([14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220331T140000&p1=179) to [16:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220331T160000&p1=179))

* [Overview of the UI/server structure](https://debruine.github.io/shinyintro/first-app.html#app-structure)
* [Inputs, outputs, and action buttons](https://debruine.github.io/shinyintro/first-app.html#dynamic-elements)
* [Reactive functions](https://debruine.github.io/shinyintro/first-app.html#first-reactive)

[ShinyDashboard](https://debruine.github.io/shinyintro/shinydashboard.html) ([16:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220331T160000&p1=179) to [18:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220331T180000&p1=179))

* [Basic template for shinydashboard projects](https://debruine.github.io/shinyintro/shinydashboard.html#basic-template-for-shinydashboard-projects)
* [Sidebar, menu navigation, and tabs](https://debruine.github.io/shinyintro/shinydashboard.html#dashboard-structure)
* [Row- and column-based layouts](https://debruine.github.io/shinyintro/shinydashboard.html#dashboardbody)

Work on the Class App ([20:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220331T200000&p1=179) to [21:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220331T140000&p1=179))

* Choose a dataset from [Tidy Tuesday](https://github.com/rfordatascience/tidytuesday)
* Set up the app UI

### Day 2

Basic Patterns ([14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220401T140000&p1=179) to [18:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220401T180000&p1=179))

* [Different input types](https://debruine.github.io/shinyintro/inputs.html)
* [Different output types](https://debruine.github.io/shinyintro/outputs.html)
* [Reactive functions](https://debruine.github.io/shinyintro/reactives.html)
* [Reading and saving data](https://debruine.github.io/shinyintro/data.html)

Work on the Class App ([20:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220401T200000&p1=179) to [21:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220401T210000&p1=179))

* Add a user-customisable data visualisation
* Add a user question to write to a googlesheet

### Day 3

Customizing Your Apps  ([14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220402T140000&p1=179) to [18:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220402T180000&p1=179))

* [HTML, CSS, and Javascript](https://debruine.github.io/shinyintro/web.html)
* [Debugging and error handling](https://debruine.github.io/shinyintro/debugging.html)
* [Contingent display](https://debruine.github.io/shinyintro/contingency.html)

